name: FitnessApp

on:
  push:
    branches: [ "master" ]
 

jobs:
  build:

    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
